# Generated by Django 5.2.4 on 2026-06-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjunto",
            name="path",
            field=models.ImageField(blank=True, null=True, upload_to="adjuntos/"),
        ),
    ]
